In [ ]:
#Decision Tree

In [ ]:
#import library
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

In [2]:
#import dataset
df=pd.read_csv('data/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2         se
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
#split data in x and y
x=df.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
type(x)

numpy.ndarray

In [5]:
y=df.iloc[:,4].values


In [6]:
#give value to the text data
from sklearn.preprocessing import LabelEncoder

In [7]:
le_y=LabelEncoder()

In [8]:
y= le_y.fit_transform(y)

In [9]:
#import train_test_split to split data in train and test model
from sklearn.model_selection import train_test_split

In [10]:
#give test size as 25%
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [11]:
#import decision tree
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [12]:
#predict values
y_pred = clf.predict(x_test)

In [13]:
y_pred

array([2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 1, 3, 1, 1, 0, 3, 1, 1, 1, 1, 3,
       3, 2, 1, 3, 3, 1, 2, 1, 3, 2, 3, 1, 1, 3, 2, 2])

In [14]:
#show train data accuracy
print("Train Data accuracy",accuracy_score(y_true = y_train, y_pred=clf.predict(x_train)))

Train Data accuracy 1.0


In [15]:
#show test data accuracy
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=y_pred))

Test data accuracy: 0.9473684210526315


In [17]:
#Random forrest
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(x_train, y_train)
y_pred = rfr.predict(x_test)

In [18]:
y_pred

array([2.  , 2.05, 2.  , 2.  , 2.  , 2.  , 1.  , 2.  , 0.83, 2.  , 3.  ,
       0.91, 3.  , 1.  , 0.88, 0.74, 2.99, 1.  , 0.93, 0.95, 1.  , 2.83,
       2.86, 2.  , 1.  , 2.94, 3.  , 0.57, 2.09, 1.  , 3.  , 2.12, 2.75,
       1.  , 0.98, 2.99, 2.02, 2.  ])