In [10]:
print("Basic numpy commands")

Basic numpy commands


In [11]:
import numpy as np 

In [23]:
b=np.array([2,3,4,7])#creating an array
print(b)

[2 3 4 7]


In [14]:
c=np.full((2,3),5) #create's an array of 5's with size 2*3 where 2 is row and 3 is column.
print(c)

[[5 5 5]
 [5 5 5]]


In [20]:
np.random.rand(3,3) #creates array 3*3 of random float values b/w 0,1 

array([[0.98703826, 0.09105926, 0.0278685 ],
       [0.0934871 , 0.20626261, 0.71619547],
       [0.3115046 , 0.81310617, 0.10005744]])

In [24]:
d=np.ones((3,2)) #creates array of values 1 with size 3*2
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
np.eye(4) #4 diogonal 1's

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
e=c.reshape(3,2) #reshape array 'c' into 3rows and 2columns
print(e)

[[5 5]
 [5 5]
 [5 5]]


In [31]:
f=np.add(d,e) #adds values of array 'd' and 'e'
print(f)

[[6. 6.]
 [6. 6.]
 [6. 6.]]


In [35]:
g=np.subtract(f,d) #suntracts values of array 'd' from 'f'
print(g)

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [38]:
h=np.multiply(f,e) #multiplys values of array 'f' and 'e'
print(h)

[[30. 30.]
 [30. 30.]
 [30. 30.]]


In [41]:
i=np.divide(f,e) #divides values of array 'f' by 'e'
print(i)

[[1.2 1.2]
 [1.2 1.2]
 [1.2 1.2]]


In [42]:
np.exp(g)

array([[148.4131591, 148.4131591],
       [148.4131591, 148.4131591],
       [148.4131591, 148.4131591]])

In [46]:
j=np.concatenate((g,f),axis=0) #concatinates array 'f' and array 'g' by row
print(j)

[[5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


In [52]:
np.delete(j,2) #deletes row 2(index) in array 'j' 

array([5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6.])

In [58]:
j[5]=7 #sets 7 as values of row 5
print(j)

[[5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [4. 4.]
 [7. 7.]]


In [59]:
j.mean() #finds mean of array 'j'

5.333333333333333

In [61]:
np.median(j) #finnds median of array 'j'


5.0

In [62]:
j[4] #prints index 4 of array 'j'

array([4., 4.])

In [69]:
j[2,1] #prints value of row 2 and column 1 "slicing"

5.0

In [66]:
np.zeros((3,2)) #creates 2d array of 3*2 and values as '0'

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
np.split(j,2) #splits array 'j' into 2 arrays

[array([[5., 5.],
        [5., 5.],
        [5., 5.]]),
 array([[6., 6.],
        [4., 4.],
        [7., 7.]])]

In [72]:
np.append(j,2) #appends element 2 in array 'j'

array([5., 5., 5., 5., 5., 5., 6., 6., 4., 4., 7., 7., 2.])

In [74]:
np.insert(j,6,1) #inserts element '1' before '6'

array([5., 5., 5., 5., 5., 5., 1., 6., 6., 4., 4., 7., 7.])

In [76]:
print(j)
j.size #shows size of array 'j'

[[5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [4. 4.]
 [7. 7.]]


12

In [81]:
j.itemsize #shows each values size

8

In [82]:
j.data

In [84]:
j.shape #shape in the form of rows and column

(6, 2)

In [85]:
j.dtype

dtype('float64')

In [88]:
j.ndim #shows dimension

2