In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('data/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2         se
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
x=df[['sepal_length','sepal_width']].values

In [13]:
x

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.1],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [10]:
x1=x['sepal_length']
y1=x['sepal_width']
x1


0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [9]:
y1

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [15]:
w=np.random.randint(2,9,size=(5,5))
w

array([[2, 8, 6, 8, 7],
       [4, 2, 6, 2, 6],
       [3, 6, 8, 2, 3],
       [5, 6, 6, 6, 3],
       [8, 4, 3, 4, 7]])

In [18]:
type(w)

numpy.ndarray

In [20]:
python={'Name':['a','g','d','r','w'],'Marks1':[65,89,32,56,23],'Marks2':[78,26,37,21,34]}
python

{'Name': ['a', 'g', 'd', 'r', 'w'],
 'Marks1': [65, 89, 32, 56, 23],
 'Marks2': [78, 26, 37, 21, 34]}

In [21]:
f=pd.DataFrame(data=python)

In [22]:
f

Name  Marks1  Marks2
0    a      65      78
1    g      89      26
2    d      32      37
3    r      56      21
4    w      23      34

In [23]:
f['total']=f['Marks1']+f['Marks2']
f

Name  Marks1  Marks2  total
0    a      65      78    143
1    g      89      26    115
2    d      32      37     69
3    r      56      21     77
4    w      23      34     57

In [24]:
h=[5,4,8,9]
g=pd.array((h))
g

<IntegerArray>
[5, 4, 8, 9]
Length: 4, dtype: Int64

In [26]:
g.max()

9

In [27]:
g.min()

4

In [34]:
type(g)

pandas.core.arrays.integer.IntegerArray

In [35]:
#f.drop(columns=['total','Marks2'])

Name  Marks1
0    a      65
1    g      89
2    d      32
3    r      56
4    w      23

In [38]:
f

Name  Marks1  Marks2  total
0    a      65      78    143
1    g      89      26    115
2    d      32      37     69
3    r      56      21     77
4    w      23      34     57

In [39]:
f.rename(columns = {'Marks1':'Mid1'}, inplace = True)
f


Name  Mid1  Marks2  total
0    a    65      78    143
1    g    89      26    115
2    d    32      37     69
3    r    56      21     77
4    w    23      34     57

In [40]:
f.rename(columns={'Marks2':'Mid2'},inplace=True)
f

Name  Mid1  Mid2  total
0    a    65    78    143
1    g    89    26    115
2    d    32    37     69
3    r    56    21     77
4    w    23    34     57

In [42]:
f.drop(['total'],axis=1)


Name  Mid1  Mid2
0    a    65    78
1    g    89    26
2    d    32    37
3    r    56    21
4    w    23    34

In [44]:
f.drop('total',axis=1)

Name  Mid1  Mid2
0    a    65    78
1    g    89    26
2    d    32    37
3    r    56    21
4    w    23    34

In [45]:
f

Name  Mid1  Mid2  total
0    a    65    78    143
1    g    89    26    115
2    d    32    37     69
3    r    56    21     77
4    w    23    34     57

In [46]:
f.drop(columns=['total'])

Name  Mid1  Mid2
0    a    65    78
1    g    89    26
2    d    32    37
3    r    56    21
4    w    23    34

In [49]:
f['final']=[67,54,32,56,43]
f

Name  Mid1  Mid2  total  final
0    a    65    78    143     67
1    g    89    26    115     54
2    d    32    37     69     32
3    r    56    21     77     56
4    w    23    34     57     43

In [53]:
f['gt']=f['total']+f['final']
f

Name  Mid1  Mid2  total  final   gt
0    a    65    78    143     67  210
1    g    89    26    115     54  169
2    d    32    37     69     32  101
3    r    56    21     77     56  133
4    w    23    34     57     43  100

In [56]:
x=df.iloc[:,0:4].values


In [99]:
y=df.iloc[:,4].values

In [100]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()

In [101]:
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [102]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [105]:
x_train.size

420

In [106]:
from sklearn.linear_model import LogisticRegression

In [107]:
lr=LogisticRegression()

In [108]:
lr.fit(x_train,y_train)

/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [109]:
y_pred=lr.predict(x_test)
y_pred

array([1, 3, 2, 2, 2, 1, 2, 1, 3, 1, 1, 2, 1, 2, 1, 2, 2, 3, 3, 1, 1, 3,
       3, 1, 1, 2, 3, 3, 3, 3, 3, 3, 1, 2, 2, 3, 2, 3, 3, 2, 1, 2, 1, 2,
       3])

In [110]:
y_pred
np.sort(y_pred)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3])

In [111]:
y_test
np.sort(y_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3])

In [113]:
from sklearn.metrics import confusion_matrix

In [114]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 12,  2],
       [ 0,  3, 14]], dtype=int64)

In [115]:
(26/30)*100

86.66666666666667

In [118]:
lr.score(x_test,y_test)

0.8888888888888888

In [120]:
from sklearn.neighbors import KNeighborsClassifier

In [125]:
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)

In [126]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [127]:
y_pred=knn.predict(x_test)
y_pred

array([1, 3, 2, 2, 2, 1, 3, 1, 3, 1, 1, 2, 1, 2, 1, 3, 2, 3, 3, 1, 1, 3,
       3, 1, 1, 2, 3, 3, 3, 3, 3, 3, 1, 2, 2, 2, 2, 3, 3, 2, 1, 2, 1, 2,
       3])

In [128]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 13,  1],
       [ 0,  1, 16]], dtype=int64)

In [129]:
(29/30)*100

96.66666666666667

In [130]:
knn.score(x_test,y_pred)

1.0

In [134]:
from sklearn.naive_bayes import GaussianNB

In [135]:
nb=GaussianNB()

In [136]:
nb.fit(x_train,y_train)

GaussianNB()

In [137]:
y_pred=nb.predict(x_test)

In [138]:
y_pred

array([1, 3, 2, 2, 2, 1, 3, 1, 3, 1, 1, 2, 1, 2, 1, 2, 2, 3, 3, 1, 1, 3,
       3, 1, 1, 2, 3, 3, 2, 3, 3, 3, 1, 2, 2, 3, 2, 2, 3, 2, 1, 2, 1, 2,
       3])

In [139]:
from sklearn.svm import SVC

In [142]:
classification=SVC(kernel='sigmoid')


In [143]:
classification

SVC(kernel='sigmoid')

In [144]:
classification.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [145]:
y_pred=classification.predict(x_test)

In [146]:
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [147]:
from sklearn.tree import DecisionTreeClassifier

In [148]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [149]:
y_pred=dtc.predict(x_test)
y_pred

array([1, 3, 3, 3, 2, 1, 3, 0, 3, 1, 1, 2, 1, 2, 1, 3, 2, 3, 3, 1, 1, 3,
       3, 1, 1, 2, 3, 3, 3, 3, 3, 3, 1, 2, 2, 3, 2, 3, 3, 2, 1, 2, 0, 2,
       3])

In [153]:
from sklearn.metrics import accuracy_score


In [154]:
accuracy_score(y_true =y_train, y_pred=dtc.predict(x_train))

1.0

In [155]:
accuracy_score(y_true= y_test, y_pred = y_pred)

0.8444444444444444

In [157]:
from sklearn.ensemble import RandomForestRegressor

In [158]:
rfr=RandomForestRegressor()

In [159]:
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [160]:
y_pred=rfr.predict(x_test)

In [161]:
y_pred

array([1.  , 3.  , 2.7 , 2.7 , 2.  , 1.  , 2.61, 0.73, 3.  , 0.96, 1.  ,
       2.  , 1.  , 2.  , 1.  , 2.83, 2.  , 3.  , 2.93, 0.72, 0.97, 2.99,
       3.  , 0.99, 1.  , 2.18, 3.  , 3.  , 2.83, 3.  , 3.  , 3.  , 0.97,
       2.  , 2.  , 3.  , 2.  , 2.83, 3.  , 2.  , 0.81, 2.  , 0.64, 2.  ,
       2.85])