In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('data/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2         se
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
df['species'].value_counts()


versicolor    50
virginica     50
setosa        49
se             1
Name: species, dtype: int64

In [10]:
x=df.iloc[0:,0:4].values

In [11]:
y=df.iloc[:,4].values

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
labelencoder_y=LabelEncoder()

In [17]:
y=labelencoder_y.fit_transform(y)

In [18]:
y

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [21]:
x_train

array([[7.1, 3. , 5.9, 2.1],
       [4.4, 3. , 1.3, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [4.8, 3.4, 1.6, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6. , 2.2, 4. , 1. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [6.3, 3.3, 6. , 2.5],
       [4.4, 2.9, 1.4, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [6.2, 2

In [22]:
x_train.size

420

In [23]:
x_test.size

180

In [24]:
y_train.size

105

In [25]:
y_test.size

45

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
y_pred=logmodel.predict(x_test)

In [30]:
y_pred
np.sort(y_pred)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3])

In [31]:
y_test
np.sort(y_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3])

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test,y_pred)

array([[18,  0,  0],
       [ 0, 14,  0],
       [ 0,  1, 12]], dtype=int64)

In [37]:
(26/30)*100

86.66666666666667

In [40]:
logmodel.score(x_test,y_pred)

1.0